name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            macOS-10.15,
            macos-latest,
            windows-2019,
            windows-latest,
            ubuntu-18.04,
            ubuntu-latest,
          ]
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
